### ISSUE TITLE
How to load m3u playlist?

### ISSUE THREAD

**Issue by ehaab** [romanvm/plugin.video.example#1]
Thanks for cool example . Does your current video code play m3u8(live and vod)streams?Furthermore , how i can load m3u playlist from a remote url?It would be helpfull if you show us an example of loading videos from m3u playlist. Thanks in advance!

**Comment by romanvm** [comment]
My intention was to provide a very basic starting point for those who are interested in creating Kodi content plugins and nothing beyond that. For other things please use Kodi Wiki and Kodi official forum.
