### ISSUE TITLE
Failed to Installed Addon from zip File

### ISSUE THREAD

**Issue by Ghayyas** [romanvm/plugin.video.example#10]
Hi, 
I was trying to made my own addon for my kodi 16.1. I Clone this video plugin example But its not working.

I just download kodi 17.4 krypton. It works fine. But Its not working on my Android box 16.1 Jarvis.

I Really Confused Please guide me what should I need to do?

**Comment by romanvm** [comment]
Phrases like "not working" are not informative at all. Please describe steps taken by you with as much details as possible, including expected results, actual results and [Kodi debug log](http://kodi.wiki/view/Log_file/Advanced) via some pastebin site.

**Comment by Ghayyas** [comment]
I mean to say that. I have cloned the repo and for testing purpose when I tried to Installed the addon on koddi it Show an error says. `FAILED TO INSTALLED ADDON FROM ZIP FILE`.
