### ISSUE TITLE
How to use custom headers with URL

### ISSUE THREAD

**Issue by eyaadh** [romanvm/plugin.video.example#14]
How can I define custom headers such as range headers for the URL for requesting partial content. Currently without range headers video seeking is not possible. I have tested the same link on VLC and seeking working perfectly. 

I am testing on KODI 18.6

**Comment by romanvm** [comment]
Kodi plugins only create listings of media items inside Kodi. They don't do or control playback, so what you are asking is not possible with the plugin API. 

Regarding your issue, Kodi does send appropriate `Range` headers automatically if the server returns `Accept-Ranges` header.

**Comment by DoM1niC** [comment]
> How can I define custom headers such as range headers for the URL for requesting partial content. Currently without range headers video seeking is not possible. I have tested the same link on VLC and seeking working perfectly.
> 
> I am testing on KODI 18.6

I use native H264 / AAC -> MP4 files and seeking works for me, I create a own API in JSON and replaced the Static Arrays in the Code with a URI to JSON Decode Stuff with success at all this Example Plugin is awesome to teach a bit in Python and learn more about Kodi and other Stuff.... in my case. 

I never sended any Headers just a HTTP redirect to file servers...

**Comment by eyaadh** [comment]
> Kodi plugins only create listings of media items inside Kodi. They don't do or control playback, so what you are asking is not possible with the plugin API.
> 
> Regarding your issue, Kodi does send appropriate `Range` headers automatically if the server returns `Accept-Ranges` header.

Actually the server returns Accept-Ranges, bellow is how the headers look like for one of the link that I am trying with the plug-in. 
```
curl -I https://node1.baivaru.net/250
HTTP/1.1 200 OK
Date: Sun, 12 Apr 2020 15:26:18 GMT
Server: Python/3.8 aiohttp/3.6.2
Content-Type: video/x-matroska
Content-Range: bytes 0-472043067/472043067
Content-Disposition: attachment; filename="The.Office.S02E10.720p.BluRay-@iMediaShare.mkv"
Accept-Ranges: bytes
Content-Length: 472043067
```
However seeking is not working with the kodi player but on external players such as VLC it works fine. I am not sure what I might have been doing wrong.

**Comment by romanvm** [comment]
Then it must be a Kodi problem. Maybe it's related to the fact that your server does not return `Content-Length` header for the file but uses `Transfer-Encoding: chunked` instead.

In any case, it is not related to this project so I'm closing this issue.
