### ISSUE TITLE
Buffering Problem

### ISSUE THREAD

**Issue by DoM1niC** [romanvm/plugin.video.example#15]
Hey I use your example Addon with some bigger Videos & on my PC all works fine but Devices with low Impact around 50mbits Bandwidth abort the Video Loading, Devices with 100Mbits or more load Videos without any problem tested on Windows/Raspberry Pi, a other Client over nativ Internet connection (external) with e.g. Windows or my Phone with Android abort instantly without any error message. 

All Devices at Kodi 18,x

**Comment by romanvm** [comment]
All Kodi plugins including this one only create listings of media items inside Kodi. They don't play anything on their own. So your issue is not related to this project.

**Comment by DoM1niC** [comment]
I fxied the Problem by creating a **advancedsettings.xml** in **userdata** with following Code...

```
<advancedsettings>
<network>
<buffermode>1</buffermode>
<readbufferfactor>1.5</readbufferfactor>
<cachemembuffersize>104857600</cachemembuffersize>
</network>
</advancedsettings>
```

there is possible to set this Settings nativ from the Addon itself ?

**Comment by romanvm** [comment]
Still not related to the plugin. As I said, plugins do not play anything by themselves, so they cannot control playback in any way.
