### ISSUE TITLE
Example video URLs are broken

### ISSUE THREAD

**Issue by Josef-Friedrich** [romanvm/plugin.video.example#17]
For example: `http://www.vidsplay.com/wp-content/uploads/2017/04/crab.mp4`

is now

`https://vod-progressive.akamaized.net/exp=1628023383~acl=%2A%2F2162790332.mp4%2A~hmac=3ffb034f65845df5fe56bd575bf1f9835bcd799224e96c56953bd44a8b29268b/vimeo-prod-skyfire-std-us/01/1631/19/483157166/2162790332.mp4?download=1&filename=crab.mp4`

**Comment by romanvm** [comment]
Replaced with public domain movies
