### ISSUE TITLE
Not compatible with https

### ISSUE THREAD

**Issue by sos-productions** [romanvm/plugin.video.example#18]
If I provide https links for videos, it is impossible to install the addon, claiming bad addon structure on kodi  Matrix 19.4

**Comment by sos-productions** [comment]
Solved, it was due to unicode problem. main.py has to be saved to utf8, else if categories contains accentuation such
as in french with é_è, then it fails.
```Error Type: <class 'SyntaxError'>
       Error Contents: (unicode error) 'utf-8' codec can't decode byte ...
```

I also added the header 

```#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literal```

**Comment by romanvm** [comment]
The current example plugin is written in Python 3 and I'd recommend to stop using Python 2.
