### ISSUE TITLE
Use listing.setArt

### ISSUE THREAD

**Issue by MartijnKaijser** [romanvm/plugin.video.example#2]
.setArt({ 'thumb': iconimage, 'banner' : os.path.join(artfolder,'banner.png'), 'fanart': os.path.join(addonfolder,'fanart.jpg') })
    liz.setPath(u)

As example code pulled from other addon

**Comment by romanvm** [comment]
Honestly, I'm not sure about this. This is a very basic example and is not supposed to cover all bases. Thumbnail and fanart images are enough for starters (especially considering the fact that the default Confulence skin simply doesn't support additional art), and if a person develops a plugin advanced enough to display additional art (logos, clearart etc.), I guess, they will read respective documentation for `ListItem` class after all.

This is not to mention the fact, that setting additional art from plugins seems to be buggy. At least, I wasn't able to make my TV-shows plugin to display additional art from fanart.tv in Aeon-Nox skin, so I gave up trying and implemented only thubms and fanart.

**Comment by MartijnKaijser** [comment]
well i know for sure poster, fanart, thumb and banner work for tvshows/episode. Could also be that skins are now doing hacks to not show it as no one did it correctly in the past.

**Comment by romanvm** [comment]
I've added `setArt` to the example. Hope, it is enough.
