### ISSUE TITLE
Remove underscores

### ISSUE THREAD

**Issue by zag2me** [romanvm/plugin.video.example#3]
From the Kodi forum thread:

One small comment: there seems to be a push to stop using **xxxx** labels in the code (I'm guessing that the format is used for internal var labels in python, so possible conflicts). See this post: http://forum.kodi.tv/showthread.php?tid=...pid2138390

**Comment by romanvm** [comment]
Please read the current code before posting issues. Your issue is not relevant any more.

**Comment by zag2me** [comment]
Thanks, noticed just after I posted ;)
