### ISSUE TITLE
Fanart support

### ISSUE THREAD

**Issue by zag2me** [romanvm/plugin.video.example#4]
Again from the Kodi thread a suggest improvement:

Seems used code is outdated although it still works. 
Should now be done with 
.setArt({ 'thumb': iconimage, 'banner' : os.path.join(artfolder,'banner.png'), 'fanart': os.path.join(addonfolder,'fanart.jpg') })  liz.setPath(u)

Code above is sample snippet and needs to be adjusted for use

http://forum.kodi.tv/showthread.php?tid=248774

**Comment by romanvm** [comment]
`setArt` indeed partially overlaps with other `ListItem` methods, like `list_item.setProperty('fanart_image', 'path/to/fanart.jpg')`, but I don't have any information that those methods  are going to be depreciated any time soon, so the current example code is still relevant.

If indeed there are plans to depreciate other methods in favor of `setArt` then I'll change the code, but I need proof of such plans.
