### ISSUE TITLE
fetch json for categories and videos?

### ISSUE THREAD

**Issue by ralyodio** [romanvm/plugin.video.example#5]
I have similar plugin, but I'd like to fetch my list from a server rather than hardcode in plugin.

**Comment by romanvm** [comment]
I'm not sure what your issue is. This was intended as a very basic example. If you need more than that you have to write your own custom logic.

**Comment by ralyodio** [comment]
I realize that I'm just look for an example of how to make an api call that returns a json response to populate the directory list

**Comment by romanvm** [comment]
I understand, but this is not an issue of this plugin.
